# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('is_manager', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_as.User'),
        ),
    ]
