# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_as', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=5)),
                ('parts', models.ManyToManyField(to='work_as.Part')),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(),
        ),
        migrations.AlterUniqueTogether(
            name='storage',
            unique_together=set([('site', 'location')]),
        ),
    ]
