# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_as', '0003_remove_part_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
