# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_as', '0005_auto_20160601_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='parts',
        ),
        migrations.AddField(
            model_name='part',
            name='storage',
            field=models.ManyToManyField(to='work_as.Storage'),
        ),
    ]
